# Generated by Django 5.2.7 on 2025-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=25)),
                ('tavsifi', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=4, max_digits=5)),
                ('mavjudligi', models.BooleanField()),
                ('kategoriya', models.CharField(choices=[('salat', 'Salat'), ('main_food', 'Main_food'), ('shirinlik', 'Shirinlik')])),
                ('rasm', models.ImageField(upload_to='')),
            ],
        ),
    ]
